version: '3.8'

services:
    api:
      container_name: api
      build:
        context: .
      volumes:
        - ./:/usr/src
      ports:
        - 8000:8000
      env_file:
        - .env/.dev
    tacacs:
      container_name: tacacs
      image: lfkeitel/tacacs_plus:alpine
      expose:
        - 49